apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: secure-reverse-proxy
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - secure-proxy.local
      secretName: secure-proxy-tls
  rules:
    - host: secure-proxy.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: secure-reverse-proxy
                port:
                  number: 80